services:
  bot:
    build: .
    container_name: meows-finance-bot-dev
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python main.py

  api:
    build: .
    container_name: meows-finance-api-dev
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:8080:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000
